// packages/engine/src/inner-plugins/default-panel-registry.tsx
import { Suspense, defineAsyncComponent } from 'vue'

const DesignerPlugin = defineAsyncComponent(() => import('./components/designer-plugin'))

// 注册默认的面板
export const defaultPanelRegistry = (editor: any) => {
  const fun = (ctx: any) => {
    return {
      init() {
        const { skeleton, config } = ctx
        skeleton.add({
          area: 'mainArea',
          name: 'designer',
          type: 'Widget',
          content: <Suspense>
            <DesignerPlugin
              engineConfig={config}
              engineEditor={editor}
            />
          </Suspense>
        })
      }
    }
  }

  fun.pluginName = '___default_panel___'

  return fun
}

// packages/engine/src/inner-plugins/default-panel-registry.jsx
import DesignerPlugin from '@cc/lowcode-plugin-designer'

export const defaultPanelRegistry = (editor) => {
  const func = (ctx) => {
    return {
      init() {
        const { skeleton, config } = ctx
        skeleton.add({
          area: 'mainArea',
          name: 'designer',
          type: 'Widget',
          content: <DesignerPlugin
            engineConfig={config}
            engineEditor={editor}
          />
        })
      }
    }
  }

  func.pluginName = '___default_panel___'

  return func
}

export default defaultPanelRegistry
